default:
  image: ruby:2.6.2

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - bundle install --with=test --path /cache
  - bundle exec rake test:models

staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=octo-stories --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
