default:
  image: ruby:2.6.2

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - bundle install --with=test --path /cache
  - bundle exec rake test:models

staging:
  stage: deploy
  script:
  - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
  - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install -y heroku-toolbelt
  - gem install dpl
  - dpl --provider=heroku --app=octo-stories --api-key=$HEROKU_STAGING_API_KEY
  # - heroku run <your command here> --exit-code --app my_heroku_app
  only:
  - master
