version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_DB=app_development
